# Config file for automatic testing at travis-ci.org

sudo: false

language: python

python:
  - 3.5
  - 3.8

envs:
  - TOXENV=quality

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.8
      env: TOXENV=py38

install:
  - pip install pip==20.0.2
  - pip install -r requirements/travis.txt

script:
  - tox
